#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : os-win
Version  : 4.3.0
Release  : 30
URL      : http://tarballs.openstack.org/os-win/os-win-4.3.0.tar.gz
Source0  : http://tarballs.openstack.org/os-win/os-win-4.3.0.tar.gz
Source99 : http://tarballs.openstack.org/os-win/os-win-4.3.0.tar.gz.asc
Summary  : Windows / Hyper-V library for OpenStack projects.
Group    : Development/Tools
License  : Apache-2.0
Requires: os-win-license = %{version}-%{release}
Requires: os-win-python = %{version}-%{release}
Requires: os-win-python3 = %{version}-%{release}
Requires: Babel
Requires: eventlet
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pbr
BuildRequires : Babel
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/os-win.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package license
Summary: license components for the os-win package.
Group: Default

%description license
license components for the os-win package.


%package python
Summary: python components for the os-win package.
Group: Default
Requires: os-win-python3 = %{version}-%{release}

%description python
python components for the os-win package.


%package python3
Summary: python3 components for the os-win package.
Group: Default
Requires: python3-core

%description python3
python3 components for the os-win package.


%prep
%setup -q -n os-win-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559920400
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os-win
cp LICENSE %{buildroot}/usr/share/package-licenses/os-win/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os-win/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
